---
registry:
  - namespace:
      - :features
    features:
      - key: :quoting_tool_app
        is_enabled: true
        meta:
          label: Quoting Tool Application
          content_type: :boolean
          default: true
          description: The Quoting Tool Application enables empployers to estimate their costs
          is_required: true
          is_visible: true
        settings:
          - key: :application_name
            item: 'quoting_tool_cca'
          - key: :site_key
            item: :ma
          - key: :state_abbreviation
            item: 'MA'
          - key: :subdomain
            item: 'ma'
          - key: :domain_name
            item: 'business.mahealthconnector.org'
          - key: :site_title
            item: 'Employer Quick Quote'
          - key: :home_url
            item: 'https://business.mahealthconnector.org/get-a-quote/'
          - key: :home_business_url
            item: 'https://business.mahealthconnector.org'
          - key: :help_url
            item: 'https://business.mahealthconnector.org/get-a-quote//help/'
          - key: :main_web_address_url
            item: 'https://business.mahealthconnector.org/'
          - key: :state_name
            item: 'Massachusetts'
          - key: :short_name
            item: 'mahealthconnector.org'
          - key: :byline
            item: "Massachusetts Health Connector for Business"
          - key: :long_name
            item: 'CoverME.gov'
          - key: :header_message
            item: "Massachusetts Health Connector for Business"
          - key: :byline
            item: "Massachusetts Health Connector for Business"
          - key: :logo_file_name
            item: 'logo_ma.svg'
          - key: :tab_icon
            item: 'favicon.ico'
          - key: :s3_prefix
            item: 'ma'
          - key: :late_rates_message
            item: 'Due to a delay, premiums for some coverage effective dates are not available yet. Please check again soon to see if this information has been updated. You can also contact Customer Service or your broker if you need help.'
          - key: :exchange_name
            item: 'CoverME.gov Health Benefit Exchange'
          - key: :state_long_title
            item: 'the state of Maine'
          - key: :minimum_length_days
            item: 5
          - key: :monthly_end_on
            item: 20
          - key: :maximum_length_months
            item: 2
          - key: :earliest_start_prior_to_effective_on_months
            item: -2
      - key: :sic_codes
        is_enabled: false
      - key: :find_my_doctor
        is_enabled: false
      - key: :benefit_model
        is_enabled: false
